
FROM gcr.io/distroless/static-debian11

COPY agent  /app/agent
EXPOSE 8080
# Command to run the executable when the container starts
CMD ["/app/agent", "web", "-port", "8080", "api", "-webui_address", "127.0.0.1:8081", "a2a", "--a2a_agent_url", "http://127.0.0.1:8081", "webui", "--api_server_address", "http://127.0.0.1:8081/api"]
				